---
- name: copy mongodb folder host
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
  
- name: Stop service mongod  
  service:
    name: mongod
    state: stopped 

- name: start mongodb
  service: 
    name: mongod
    state: started

- name: create prime replica set
  shell: mongo --eval "rs.initiate()"
  when: groups.mongo.index(inventory_hostname) == 0

- name: add members to prime
  shell: mongo --eval '{{ mongo_commend}}'
  with_items: "{{ groups.mongo }}"
  when: groups.mongo.index(inventory_hostname) == 0
